FROM heroku/nuclear-waster-on-twitter

# Grab requirements.txt
ADD ./requirements.txt /tmp/requirements.txt

# Install dependencies
RUN pip install -qr /tmp/requirements.txt

# Add our code
ADD ./
WORKDIR ./

CMD gunicorn --bind 0.0.0.0:$PORT 33507